name: Build and Push Docs folder

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Get npm packages
        run: npm ci

      - name: Build
        run: node --run sync && node --run sitemap:generate && node --run build

      - name: Upload ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './docs/'
          server-dir: '/'
          dry-run: true
